name: Build and Deploy to Anypoint Platform

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'
      - name: Build with Maven
        run: mvn -B package --file pom.xml
      - name: Stamp artifact file name with commit hash
        run: |
          artifactName1=$(ls target/*.jar | head -1)
          commitHash=$(git rev-parse --short "$GITHUB_SHA")
          artifactName2=$(ls target/*.jar | head -1 | sed "s/.jar/.$commitHash.jar/g")
          mv $artifactName1 $artifactName2
      - uses: actions/upload-artifact@v3
        with:
            name: artifacts
            path: target/*.jar

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v3
        with:
          name: artifacts

      - name: Deploy to Anypoint Platform
        env:
          ANYPONT_USERNAME: ${{ secrets.ANYPOINT_USERNAME }}
          ANYPONT_PASSWORD: ${{ secrets.ANYPOINT_PASSWORD }}
          ANYPONT_APP_NAME: 'try-cicd'  # Replace with your application name
          JAR_FILE: 'target/*.jar'  # Adjust if necessary
        run: |
          # Log in to Anypoint Platform and get an access token
          ACCESS_TOKEN=$(curl -s -X POST https://anypoint.mulesoft.com/accounts/api/v2/login \
            -H 'Content-Type: application/json' \
            -d "{\"username\":\"$ANYPOINT_USERNAME\", \"password\":\"$ANYPOINT_PASSWORD\"}" | jq -r .access_token)

          # Deploy the JAR file
          curl -X POST https://anypoint.mulesoft.com/apimanager/api/v1/organizations/$ANYPONT_ORG_ID/applications \
            -H "Authorization: Bearer $ACCESS_TOKEN" \
            -H 'Content-Type: application/json' \
            -d '{
              "name": "'"$ANYPONT_APP_NAME"'",
              "version": "1.0.0",
              "environmentId": "'"$ANYPONT_ENVIRONMENT_ID"'",
              "applicationId": "'"$ANYPONT_APP_NAME"'",
              "artifact": "'"$JAR_FILE"'"
            }'

          echo "Deployment completed!"
